- name: Google Cloud Provision
  hosts: localhost
  tasks:
    - name: provision api instance
      gce:
        instance_names: api-instance
        zone: us-central1-a
        machine_type: f1-micro
        image: debian-8
        state: present
        #service_account_email: "{{ ansible_env.MYGCLCLICONFIG_INTEGRATION_JSON_KEY | jq -r 'client_email' }}"
        credentials_file: "{{ ansible_env.MYGCLCLICONFIG_INTEGRATION_JSON_KEY}}"
        #project_id: "{{ ansible_env.MYGCLCLICONFIG_INTEGRATION_JSON_KEY | jq -r 'project_id' }}"
